services:
  dev-mysql-db:
    container_name: dev-mysql-db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "jabs"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"

  stg-db-server:
    container_name: stg-db-server
    image: postgres:17-alpine3.21
    restart: always
    environment:
      POSTGRES_DB: "jabs"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

