services:
  dev-mysql-db:
    container_name: dev-mysql-db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "jabs"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"

  stg-db-server:
    container_name: stg-db-server
    image: postgres:17-alpine3.21
    restart: always
    environment:
      POSTGRES_DB: "jabs"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./src/main/java/com/kdob/jabs/task6/prometheus/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./src/main/java/com/kdob/jabs/task6/grafana/dashboard:/etc/grafana/provisioning/dashboards/jabs
      - ./src/main/java/com/kdob/jabs/task6/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"

volumes:
  prometheus_data: {}
  grafana_data: {}
