spring:
  # Database Configuration
  datasource:
#    create a database in a file with parallel access
    url: jdbc:h2:file:./data/jabs;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: username
    password: password
    driver-class-name: org.h2.Driver

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
