spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/jabs_prod
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 120000
      connection-timeout: 30000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Disable debug logging for production
logging:
  level:
    org.springframework.security: INFO
    org.springframework: INFO
    com.kdob.jabs: INFO